from ..extensions import db

SEED_VCS = [
    {
        "name": "Y Combinator",
        "description": "Twice-yearly accelerator backing early-stage startups across all sectors. Widely considered the most prestigious startup program in the world.",
        "website": "https://www.ycombinator.com",
        "hq_city": "San Francisco, CA",
        "founded_year": 2005,
        "focus_sectors": "SaaS, Consumer, Fintech, Healthcare, Developer Tools, AI, Hardware",
        "stages": "Pre-seed, Seed",
        "check_min_k": 125,
        "check_max_k": 500,
        "aum_usd_bn": None,
        "notable_portfolio": "Airbnb, Stripe, Dropbox, Coinbase, DoorDash, Reddit",
    },
    {
        "name": "Andreessen Horowitz",
        "description": "One of the most influential VC firms, running dedicated funds across crypto, bio, consumer, and enterprise.",
        "website": "https://a16z.com",
        "hq_city": "Menlo Park, CA",
        "founded_year": 2009,
        "focus_sectors": "Enterprise, Consumer, Fintech, Crypto, Bio, AI, Gaming",
        "stages": "Seed, Series A, Series B, Series C, Growth",
        "check_min_k": 1000,
        "check_max_k": 150000,
        "aum_usd_bn": 35.0,
        "notable_portfolio": "GitHub, Lyft, Slack, Okta, Figma, Roblox, OpenSea",
    },
    {
        "name": "Sequoia Capital",
        "description": "Legendary firm with over 50 years of backing category-defining companies from inception through IPO.",
        "website": "https://www.sequoiacap.com",
        "hq_city": "Menlo Park, CA",
        "founded_year": 1972,
        "focus_sectors": "Consumer, Enterprise, Healthcare, Fintech, Deep Tech, AI",
        "stages": "Seed, Series A, Series B, Series C, Growth",
        "check_min_k": 1000,
        "check_max_k": 200000,
        "aum_usd_bn": 85.0,
        "notable_portfolio": "Apple, Google, WhatsApp, Airbnb, Stripe, Zoom, Snowflake",
    },
    {
        "name": "Benchmark",
        "description": "Concentrated partnership-model fund focused on early-stage bets in consumer and enterprise technology.",
        "website": "https://www.benchmark.com",
        "hq_city": "San Francisco, CA",
        "founded_year": 1995,
        "focus_sectors": "Consumer, Enterprise, Marketplace",
        "stages": "Series A, Series B",
        "check_min_k": 5000,
        "check_max_k": 25000,
        "aum_usd_bn": 3.0,
        "notable_portfolio": "eBay, Twitter, Uber, Snapchat, Discord, Stitch Fix",
    },
    {
        "name": "Accel",
        "description": "Global firm with deep expertise in enterprise software, security, and consumer internet across the US and Europe.",
        "website": "https://www.accel.com",
        "hq_city": "Palo Alto, CA",
        "founded_year": 1983,
        "focus_sectors": "Enterprise, Security, Consumer, Fintech, SaaS",
        "stages": "Seed, Series A, Series B",
        "check_min_k": 5000,
        "check_max_k": 30000,
        "aum_usd_bn": 17.0,
        "notable_portfolio": "Facebook, Spotify, Slack, Dropbox, CrowdStrike, Atlassian",
    },
    {
        "name": "Lightspeed Venture Partners",
        "description": "Multi-stage firm with global presence, particularly active in consumer, enterprise, and healthtech.",
        "website": "https://lsvp.com",
        "hq_city": "Menlo Park, CA",
        "founded_year": 2000,
        "focus_sectors": "Consumer, Enterprise, HealthTech, Fintech, AI",
        "stages": "Seed, Series A, Series B",
        "check_min_k": 2000,
        "check_max_k": 30000,
        "aum_usd_bn": 25.0,
        "notable_portfolio": "Snapchat, Affirm, Nutanix, AppDynamics, Epic Games, MuleSoft",
    },
    {
        "name": "First Round Capital",
        "description": "Seed-stage firm known for its strong founder community, peer network, and hands-on operational support.",
        "website": "https://firstround.com",
        "hq_city": "San Francisco, CA",
        "founded_year": 2004,
        "focus_sectors": "SaaS, Consumer, Fintech, Healthcare, Developer Tools",
        "stages": "Seed, Series A",
        "check_min_k": 500,
        "check_max_k": 5000,
        "aum_usd_bn": 3.0,
        "notable_portfolio": "Uber, Square, Warby Parker, Notion, Roblox, Flatiron Health",
    },
    {
        "name": "Index Ventures",
        "description": "European-rooted firm with a strong global presence in fintech, SaaS, and consumer internet.",
        "website": "https://www.indexventures.com",
        "hq_city": "London / San Francisco",
        "founded_year": 1996,
        "focus_sectors": "Fintech, SaaS, Consumer, Gaming, Marketplace",
        "stages": "Seed, Series A, Series B",
        "check_min_k": 2000,
        "check_max_k": 30000,
        "aum_usd_bn": 9.0,
        "notable_portfolio": "Dropbox, Robinhood, Figma, Datadog, Notion, Discord",
    },
    {
        "name": "General Catalyst",
        "description": "Multi-stage firm focused on transformative companies in healthcare, climate, and enterprise AI.",
        "website": "https://www.generalcatalyst.com",
        "hq_city": "Cambridge, MA",
        "founded_year": 2000,
        "focus_sectors": "Healthcare, Enterprise, Climate, Fintech, AI",
        "stages": "Series A, Series B, Series C",
        "check_min_k": 5000,
        "check_max_k": 50000,
        "aum_usd_bn": 25.0,
        "notable_portfolio": "Stripe, Airbnb, Snap, HubSpot, Canva, Mistral",
    },
    {
        "name": "Bessemer Venture Partners",
        "description": "One of the oldest VC firms, pioneering cloud investing and vertical SaaS for over a century.",
        "website": "https://www.bvp.com",
        "hq_city": "San Francisco, CA",
        "founded_year": 1911,
        "focus_sectors": "Cloud, SaaS, Security, Consumer, Healthcare",
        "stages": "Seed, Series A, Series B",
        "check_min_k": 2000,
        "check_max_k": 25000,
        "aum_usd_bn": 20.0,
        "notable_portfolio": "Shopify, LinkedIn, Twilio, Yelp, Wix, Canva, PagerDuty",
    },
    {
        "name": "GV (Google Ventures)",
        "description": "Alphabet's venture arm focusing on deep tech, life sciences, and enterprise with Google's network as leverage.",
        "website": "https://www.gv.com",
        "hq_city": "Mountain View, CA",
        "founded_year": 2009,
        "focus_sectors": "Deep Tech, Life Sciences, Enterprise, AI, Climate",
        "stages": "Seed, Series A, Series B",
        "check_min_k": 1000,
        "check_max_k": 30000,
        "aum_usd_bn": 8.0,
        "notable_portfolio": "Uber, Slack, Duolingo, Flatiron Health, Verily, Foundation Medicine",
    },
    {
        "name": "Khosla Ventures",
        "description": "Contrarian deep-tech investor making bold bets in climate, health, and frontier technology.",
        "website": "https://www.khoslaventures.com",
        "hq_city": "Menlo Park, CA",
        "founded_year": 2004,
        "focus_sectors": "Climate, Healthcare, AI, Deep Tech, Energy, Food Tech",
        "stages": "Seed, Series A, Series B, Growth",
        "check_min_k": 500,
        "check_max_k": 50000,
        "aum_usd_bn": 15.0,
        "notable_portfolio": "DoorDash, Square, Impossible Foods, OpenAI, Instacart",
    },
    {
        "name": "Union Square Ventures",
        "description": "Thesis-driven early-stage fund focused on large decentralized networks, crypto, and open protocols.",
        "website": "https://www.usv.com",
        "hq_city": "New York, NY",
        "founded_year": 2003,
        "focus_sectors": "Consumer Internet, Crypto, Education, Healthcare, Climate",
        "stages": "Seed, Series A",
        "check_min_k": 1000,
        "check_max_k": 10000,
        "aum_usd_bn": 2.0,
        "notable_portfolio": "Twitter, Coinbase, MongoDB, Duolingo, Etsy, Cloudflare",
    },
    {
        "name": "Founders Fund",
        "description": "Peter Thiel's contrarian fund betting on frontier technology, scientific breakthroughs, and national security.",
        "website": "https://foundersfund.com",
        "hq_city": "San Francisco, CA",
        "founded_year": 2005,
        "focus_sectors": "Deep Tech, Defense, AI, Biotech, Space, Crypto",
        "stages": "Seed, Series A, Series B, Growth",
        "check_min_k": 1000,
        "check_max_k": 50000,
        "aum_usd_bn": 11.0,
        "notable_portfolio": "SpaceX, Palantir, Lyft, Airbnb, Spotify, Anduril",
    },
    {
        "name": "Tiger Global Management",
        "description": "Growth-stage crossover fund known for fast decisions and large check sizes across global tech.",
        "website": "https://www.tigerglobal.com",
        "hq_city": "New York, NY",
        "founded_year": 2001,
        "focus_sectors": "Consumer, Enterprise, Fintech, SaaS, E-Commerce",
        "stages": "Series B, Series C, Growth",
        "check_min_k": 50000,
        "check_max_k": 500000,
        "aum_usd_bn": 90.0,
        "notable_portfolio": "Facebook, LinkedIn, Spotify, Peloton, Stripe, Databricks",
    },
    {
        "name": "Coatue Management",
        "description": "Data-driven crossover fund investing in high-growth tech companies from Series B through the public markets.",
        "website": "https://www.coatue.com",
        "hq_city": "New York, NY",
        "founded_year": 1999,
        "focus_sectors": "Consumer, Enterprise, Fintech, AI, SaaS",
        "stages": "Series B, Series C, Growth",
        "check_min_k": 50000,
        "check_max_k": 300000,
        "aum_usd_bn": 50.0,
        "notable_portfolio": "Snap, ByteDance, DoorDash, Lyft, Chime, Scale AI",
    },
    {
        "name": "Insight Partners",
        "description": "Software-focused growth equity firm helping ScaleUp companies worldwide with deep operational support.",
        "website": "https://www.insightpartners.com",
        "hq_city": "New York, NY",
        "founded_year": 1995,
        "focus_sectors": "SaaS, Enterprise Software, Cloud, Security, Fintech",
        "stages": "Series B, Series C, Growth",
        "check_min_k": 20000,
        "check_max_k": 200000,
        "aum_usd_bn": 90.0,
        "notable_portfolio": "Twitter, Shopify, Wix, JFrog, monday.com, Qualtrics",
    },
    {
        "name": "Battery Ventures",
        "description": "Enterprise-focused firm with a long track record in application software and industrial technology.",
        "website": "https://www.battery.com",
        "hq_city": "Boston, MA",
        "founded_year": 1983,
        "focus_sectors": "Enterprise Software, Industrial Tech, Security, SaaS",
        "stages": "Series A, Series B",
        "check_min_k": 5000,
        "check_max_k": 50000,
        "aum_usd_bn": 13.0,
        "notable_portfolio": "Groupon, Wayfair, Coupa Software, Glassdoor, 6sense",
    },
    {
        "name": "NEA",
        "description": "One of the largest VC firms, investing from seed through growth across life sciences and technology.",
        "website": "https://www.nea.com",
        "hq_city": "Menlo Park, CA",
        "founded_year": 1977,
        "focus_sectors": "Healthcare, Life Sciences, Enterprise, Consumer, Deep Tech",
        "stages": "Seed, Series A, Series B, Series C",
        "check_min_k": 2000,
        "check_max_k": 40000,
        "aum_usd_bn": 25.0,
        "notable_portfolio": "Salesforce, Robinhood, Cloudflare, Plaid, Coursera",
    },
    {
        "name": "Initialized Capital",
        "description": "Seed fund co-founded by Garry Tan and Alexis Ohanian, backing founders at the earliest stage.",
        "website": "https://initialized.com",
        "hq_city": "San Francisco, CA",
        "founded_year": 2012,
        "focus_sectors": "SaaS, Consumer, Fintech, Healthcare, Developer Tools",
        "stages": "Pre-seed, Seed",
        "check_min_k": 500,
        "check_max_k": 2000,
        "aum_usd_bn": 0.7,
        "notable_portfolio": "Coinbase, Instacart, Flexport, OpenSea, Patreon",
    },
    {
        "name": "Precursor Ventures",
        "description": "Pre-seed fund with a mission to back underrepresented founders building category-creating companies.",
        "website": "https://precursorvc.com",
        "hq_city": "San Francisco, CA",
        "founded_year": 2015,
        "focus_sectors": "SaaS, Consumer, Healthcare, Fintech, Future of Work",
        "stages": "Pre-seed",
        "check_min_k": 100,
        "check_max_k": 500,
        "aum_usd_bn": 0.2,
        "notable_portfolio": "Andela, Finix, Valence, Beam Dental",
    },
    {
        "name": "Techstars",
        "description": "Global accelerator running 3-month cohorts in dozens of cities, offering mentorship and a powerful alumni network.",
        "website": "https://www.techstars.com",
        "hq_city": "Boulder, CO",
        "founded_year": 2006,
        "focus_sectors": "SaaS, Healthcare, Fintech, Consumer, IoT, AI",
        "stages": "Pre-seed",
        "check_min_k": 120,
        "check_max_k": 120,
        "aum_usd_bn": None,
        "notable_portfolio": "SendGrid, DigitalOcean, PillPack, ClassPass, Chainalysis",
    },
    {
        "name": "500 Global",
        "description": "Seed-stage firm investing in underrepresented founders and emerging markets globally.",
        "website": "https://500.co",
        "hq_city": "San Francisco, CA",
        "founded_year": 2010,
        "focus_sectors": "SaaS, Consumer, Fintech, Healthcare, Emerging Markets",
        "stages": "Pre-seed, Seed",
        "check_min_k": 150,
        "check_max_k": 1000,
        "aum_usd_bn": 2.7,
        "notable_portfolio": "Canva, Talkdesk, Grab, Udemy, Credit Karma",
    },
    {
        "name": "Matrix Partners",
        "description": "Early-stage fund with decades of experience in enterprise software and consumer internet.",
        "website": "https://www.matrixpartners.com",
        "hq_city": "San Francisco, CA",
        "founded_year": 1977,
        "focus_sectors": "Enterprise Software, Consumer, Marketplace, SaaS",
        "stages": "Series A, Series B",
        "check_min_k": 5000,
        "check_max_k": 30000,
        "aum_usd_bn": 6.0,
        "notable_portfolio": "HubSpot, Zendesk, Oculus, Quora, Veeva Systems, Loom",
    },
]


def seed_vc_firms():
    from ..models.models import VCFirm
    for v in SEED_VCS:
        if not VCFirm.query.filter_by(name=v["name"]).first():
            db.session.add(VCFirm(**v))
    db.session.commit()
